# Generated by Django 4.0.3 on 2022-04-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_contact_alter_doctor_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contact1',
        ),
    ]
