# Generated by Django 4.0.3 on 2022-04-05 09:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0002_doctor_facebook_doctor_instagram_doctor_linkedin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('date', models.TimeField(default=datetime.datetime(2022, 4, 5, 11, 32, 0, 449412))),
                ('messages', models.TextField()),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.department')),
                ('doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.doctor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
