# Generated by Django 4.0.3 on 2022-04-05 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_appointment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.TimeField(default=datetime.datetime(2022, 4, 5, 12, 52, 27, 275063)),
        ),
    ]
