# Generated by Django 4.0.3 on 2022-04-05 10:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_doctor_facebook_doctor_instagram_doctor_linkedin_and_more'),
        ('accounts', '0007_appointment_department_n_appointment_doctor_n_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.TimeField(default=datetime.datetime(2022, 4, 5, 12, 57, 20, 664810)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='department_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.department'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.doctor'),
        ),
    ]
