# Generated by Django 4.0.3 on 2022-04-05 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_appointment_department_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='department_n',
            new_name='department_name',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='doctor_n',
            new_name='doctor_name',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.TimeField(default=datetime.datetime(2022, 4, 5, 13, 7, 2, 881572)),
        ),
    ]
