# Generated by Django 4.0.3 on 2022-04-05 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.TimeField(default=datetime.datetime(2022, 4, 5, 16, 2, 32, 838090)),
        ),
    ]
